### ISSUE TITLE
build failed :(

### ISSUE THREAD

**Issue by thundergreen** [patagonaa/homeassistant-unifi-led#1]
Hello I tried building your nice docker wunder Ubuntu and get this error .. any idea=

```
Building app
Step 1/10 : FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
 ---> 52a3845cafb1
Step 2/10 : WORKDIR /app/src
 ---> Using cache
 ---> 5df100b85216
Step 3/10 : COPY src/HomeAssistantUnifiLed/HomeAssistantUnifiLed.csproj /app/src/HomeAssistantUnifiLed/
 ---> Using cache
 ---> 854d06646fe0
Step 4/10 : RUN dotnet restore HomeAssistantUnifiLed/HomeAssistantUnifiLed.csproj
 ---> Using cache
 ---> f0a913210d41
Step 5/10 : COPY src/ /app/src
 ---> Using cache
 ---> dfb87dc29ff7
Step 6/10 : RUN dotnet publish -c Release HomeAssistantUnifiLed/HomeAssistantUnifiLed.csproj -o /app/build
 ---> Running in 729118a8c598
Microsoft (R) Build Engine version 16.7.2+b60ddb6f4 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Skipping project "/app/src/dotnet-homeassistant-mqtt-discovery/src/HomeAssistantDiscoveryHelper/HomeAssistantDiscoveryHelper.csproj" because it was not found.
  Skipping project "/app/src/dotnet-homeassistant-mqtt-discovery/src/HomeAssistantDiscoveryHelper/HomeAssistantDiscoveryHelper.csproj" because it was not found.
  All projects are up-to-date for restore.
/usr/share/dotnet/sdk/3.1.405/Microsoft.Common.CurrentVersion.targets(1850,5): warning : The referenced project '../dotnet-homeassistant-mqtt-discovery/src/HomeAssistantDiscoveryHelper/HomeAssistantDiscoveryHelper.csproj' does not exist. [/app/src/HomeAssistantUnifiLed/HomeAssistantUnifiLed.csproj]
Program.cs(1,7): error CS0246: The type or namespace name 'HomeAssistantDiscoveryHelper' could not be found (are you missing a using directive or an assembly reference?) [/app/src/HomeAssistantUnifiLed/HomeAssistantUnifiLed.csproj]
ERROR: Service 'app' failed to build : The command '/bin/sh -c dotnet publish -c Release HomeAssistantUnifiLed/HomeAssistantUnifiLed.csproj -o /app/build' returned a non-zero code: 1
hassio@HassIO-Server:/media/hassio/USB-HDD/Docker/homeassistant-unifi-led$ 

```

**Comment by patagonaa** [comment]
Seems like you didn't clone the repo recusively (thanks git for not warning about submodules in a repo...). There's supposed to be a submodule in `src/dotnet-homeassistant-mqtt-discovery`.
`git pull --recurse-submodules` or `git submodule update --init --recursive` should get it up and running.

**Comment by thundergreen** [comment]
@patagonaa cool! it built corretly .. now i have : ```Connected to 192.168.1.22``` which is my AP. But i don't see anything in Home-Assistant in MQTT component :( so i have to restart Home-Assistant and how would I use you wonderful app for 3 AP in the same time?

EDIT Restarting Home-assistant did not make the light appear  :(

I am running those frimware on the AP:

```

4.3.24.11355 
```

**Comment by patagonaa** [comment]
You can add multiple APs to the config. Also, you can set a name for Home Assistant if you're using an IP instead of a hostname.:
```
{
    "Mqtt": {
        "Host": "mqtt.example.com",
        "Username": "example",
        "Password": "secret"
    },
    "Devices": [
        {
            "Name": "unifi-ap-1",
            "Host": "192.168.178.12",
            "Username": "root",
            "Password": "secret"
        },
        {
            "Name": "unifi-ap-2",
            "Host": "192.168.178.13",
            "Username": "root",
            "Password": "secret"
        }
    ]
}
```
Each access point should show up as a device in Home Assistant with the configured name (if set) or host/ip.
You can try looking at the log output of the docker container if there is anything else suspicious (issues with MQTT or with connecting to the access points)

**Comment by thundergreen** [comment]
That's weird.

my config:

```
{
    "Mqtt": {
        "Host": "192.168.1.41",
        "Username": "hass",
        "Password": "hass"
    },
    "Devices": [
        {
            "Name": "unifi-ap-1",
            "Host": "192.168.1.22",
            "Username": "admin",
            "Password": "jnGywbQBV5oWxz5V"
        }
    ]
}

```
but no devices / entity with either IP address or NAme :( nothing in logs but Connected as shown above. Is there a debug available somehow for the container?

**Comment by thundergreen** [comment]
All right! I got an entity  :) Worked after adding the name to the device :)Cool! I will have to increase the brightness on the econtroller i guess as i don't see the blue but the white. Not possible with you integration right? would be anice feature to change brightness as well :)  Thanks so far will add the other APs also :)

**Comment by patagonaa** [comment]
The LED can only be set on/off using the controller (to my knowledge), also the blue LED is really dim, so it can be hard to see even if it works.

**Comment by thundergreen** [comment]
OK.. thanks for clarifying this :) It's too bright now to see it. Any idea where to change ethe brightness? In unifi controller i can set the brightness but it wont have any result / change :(

**Comment by patagonaa** [comment]
To my knowledge, there's no way to change the brightness for the LEDs, this is as bright as it will go.
The brightness slider in the controller is only for the screen brightness for Unifi devices like switches or routers.

**Comment by patagonaa** [comment]
(also, as a hint: you should probably be more careful with posting passwords, auth keys and such on the internet)

**Comment by thundergreen** [comment]
indeed :)

**Comment by thundergreen** [comment]
I successfully added my other APs :) Thanks again! Will share this on Home-Assistant Forum :)
