### ISSUE TITLE
Support for version 5.43.

### ISSUE THREAD

**Issue by MattXcz** [patagonaa/homeassistant-unifi-led#2]
Hello,
new release of AP will only turn on / off led for couple of seconds.
Then, it will return to initial state.

**Comment by patagonaa** [comment]
fixed in 8110661612999b8ba521129645867c8b950eb39c using the method described in https://community.home-assistant.io/t/control-unifi-ap-status-led/188063

sorry it took so long, but I didn't get around to really have a look at this earlier
