### ISSUE TITLE
Is it working?

### ISSUE THREAD

**Issue by clipse2004** [patagonaa/homeassistant-unifi-led#4]
Hey dude,

does it working for you at the Moment? 
The cointainer is running and my config (name + ip) is correct. The light shows in HA but if i click on it nothing change.
Log says:
Connected to 192.168.1.1
AP 192.168.1.1 Color white ON
AP 192.168.1.1 Color white OFF
AP 192.168.1.1 Color white OFF
AP 192.168.1.1 Color white OFF
AP 192.168.1.1 Color white ON
AP 192.168.1.1 Color white OFF
AP 192.168.1.1 Color white ON
AP 192.168.1.1 Color white OFF

Manuell with ssh it works but not persistent.

thx dude

**Comment by clipse2004** [comment]
ok my Access Points working but not the dreammachine. does it only works with aps or should with dreammachine too?

**Comment by patagonaa** [comment]
I've only tested this with access points, probably the command for the dream machine is different, idk
